print("hello word")
print("100 + 50 =")
print(100 + 50)
print("My Name is \"Deivis\" \n I\'m Learning Python")
print("A\tB\tC")
print("tu tienes" + " " + input("coloca tu edad: ") + " " + ("años"))
print(input("qué estás estudiando "))
print(input("Escribe tu nombre ") + " " + input("Escribe tu apellido "))
